# Generated by Django 5.0.6 on 2024-05-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
        ('users_app', '0002_delete_blog_delete_blogimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimages',
            name='image_ppoi',
        ),
        migrations.RemoveField(
            model_name='blogimages',
            name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs_app.blogimages'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.FileField(upload_to='blog_images/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users_app.profile')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img', to='blogs_app.blogimages')),
            ],
        ),
    ]
