# Generated by Django 5.0.6 on 2024-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0003_imagefiles_remove_image_image_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
        migrations.DeleteModel(
            name='ImageFiles',
        ),
    ]
