# Generated by Django 5.0.6 on 2024-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_alter_postimages_image_delete_imagefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog_images/')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(to='blogs_app.uploadimage'),
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
